name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: folke/github/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      plugin: tokyonight.nvim
      repo: cdmistman/tokyonight.nvim
